// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3cEY1xyrrKLxZNZtNt57CFBWnSnzdlQ',
    appId: '1:748273794330:web:527a799ad652f8ec9f00a3',
    messagingSenderId: '748273794330',
    projectId: 'gearguard-72bb7',
    authDomain: 'gearguard-72bb7.firebaseapp.com',
    storageBucket: 'gearguard-72bb7.firebasestorage.app',
    measurementId: 'G-EFVLVXZYRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwy8bac6PwFNjrXPZ_eFZit30Jhr9bUf4',
    appId: '1:748273794330:android:0cfb51c8c54d932d9f00a3',
    messagingSenderId: '748273794330',
    projectId: 'gearguard-72bb7',
    storageBucket: 'gearguard-72bb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Df5EJnJK5HEHIPMI5JqsJKZTgysswhg',
    appId: '1:748273794330:ios:166e3117827f5bc39f00a3',
    messagingSenderId: '748273794330',
    projectId: 'gearguard-72bb7',
    storageBucket: 'gearguard-72bb7.firebasestorage.app',
    iosBundleId: 'com.example.odooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Df5EJnJK5HEHIPMI5JqsJKZTgysswhg',
    appId: '1:748273794330:ios:166e3117827f5bc39f00a3',
    messagingSenderId: '748273794330',
    projectId: 'gearguard-72bb7',
    storageBucket: 'gearguard-72bb7.firebasestorage.app',
    iosBundleId: 'com.example.odooApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk3cEY1xyrrKLxZNZtNt57CFBWnSnzdlQ',
    appId: '1:748273794330:web:c1c6c820ba01ca119f00a3',
    messagingSenderId: '748273794330',
    projectId: 'gearguard-72bb7',
    authDomain: 'gearguard-72bb7.firebaseapp.com',
    storageBucket: 'gearguard-72bb7.firebasestorage.app',
    measurementId: 'G-GDTLQ4JX3E',
  );
}
